#!/bin/sh
# $Id$
# $HeadURL$
# $LastChangedDate$
#
# Script to build a distribution package.

set -e
	
if [ "$1" = "" ]; then
	echo "Please specify a version number!"
	exit 1
fi

if [ -d ../primemover-$1 ]; then
	echo "I think you've already generated version $1."
	exit 1
fi

./build
mkdir ../primemover-$1

tar cf - . --exclude=.svn --exclude=".pm*" | (cd ../primemover-$1; tar xf -) 
rm ../primemover-$1/mkdist

(cd .. && tar cvf primemover-$1.tar.bz2 --bzip2 primemover-$1)

echo ""
echo "Done --- but did you remember to update the version number in the README and pm.lua?"

